---
title: Doe mee aan Coolest Projects
hero_image: images/banner.png
description: Doe mee aan Coolest Projects, dé technologie showcase voor jongeren
version: 4
listed: false
copyedit: false
last_tested: "2021-11-19"
steps:
  - 
    title: Doe mee aan Coolest Projects
