---
title: Take part in Coolest Projects
hero_image: images/banner.png
description: Take part in Coolest Projects, the world’s leading technology showcase for young people
version: 4
listed: false
copyedit: false
last_tested: "2021-11-19"
steps:
  - 
    title: Take part in Coolest Projects
